export const data = [
	{
		title: 'Egg sauce',
		img: '/img/a.jpg',
		para: 'Egg sauce It’s typically one of staple food that is perfect for breakfast.',
		price: '150',
		availability:'Available',
		type: 'breakfast',
		id: 1,
	},
	{
		title: 'Boiled plaintain',
		img: '/img/dm4a.jpg',
		para: 'Boiled plaintain are highly nutritious for everyone, boiled plaintain ',
		price: '2000',
		availability:'out of stock',
		type: 'dinner',
		id: 2,
	},
	{
		title: 'Boiled Potatoes',
		img: '/img/pot.jpg',
		para: 'Boiled potatoes are highly nutritious mostly for kids & contains fiber.',
		price: '1000',
		availability:'Available',
		type: 'dinner',
		id: 3,
	},
	{
		title: 'Grilled plantain',
		img: '/img/sm3.jpg',
		para: 'Grilled plantain are  mainly made with roasted groundnut ',
		price: '300',
		availability:'Available',
		type: 'snacks',
		id: 4,
	},
	{
		title: 'Akara and Pap',
		img: '/img/akp.jpg',
		para: 'Akara and Pap is Naija’s weekend morning meal for most homes .',
		price: '300',
		availability:'Available',
		type: 'breakfast',
		id: 5,
	},
	{
		title: 'Pounded yam and egusi soup',
		img: '/img/lm3.jpg',
		para: 'Pounded Yam and egusi is a very delicious meal.',
		price: '2000',
		availability:'Out of stock',
		type: 'lunch',
		id: 6,
	},
	{
		title: 'Spagetti',
		img: '/img/sap.jpg',
		para: ' spaggetti is a starchy pasta of Italian origin that is made of long strings',
		price: '1500',
		availability:'Available',
		type: 'dinner',
		id: 7,
	},
	{
		title: 'Puff Puff',
		img: '/img/pu.jpg',
		para: 'Puff-puff, as it is called in India and Sierra Leone, sometimes Ghana.',
		price: '200',
		availability:'Out of stock',
		type: 'snacks',
		id: 8,
	},
	{
		title: 'Toast Bread and Tea',
		img: '/img/Tob.jpg',
		para: 'Most homes in nigeria love our bread toasted but served with sauce ',
		price: '1000',
		availability:'Available',
		type: 'breakfast',
		id: 9,
	},
	{
		title: 'Jollof rice',
		img: '/img/lm1.jpg',
		para: 'Jollof, or jollof rice, is a rice dish from West Africa..',
		price: '2000',
		availability:'Available',
		type: 'lunch',
		id: 10,
	},
	{
		title: 'Abacha',
		img: '/img/lm5.jpg',
		para: 'African salad is native to the ndi Igbo (people of Igbo).',
		price: '3000',
		availability:'Out of stock',
		type: 'lunch',
		id: 11,
	},
	
		{
			title: 'corn',
			img: '/img/corn.jpg',
			para: 'corn can highly nutritious and can be eaten roasted,',
			price: '500',
			availability:'Available',
			type: 'snacks',
			id: 12,
			
		},
		{
			title: 'Choclate-cake',
			img: '/img/ing.jpg',
			para: 'Chocolate cake is made with melted chocolate, cocoa powder, or both',
			price: '100',
			availability:'Available',
			type: 'snacks',
			id: 13,
			
		},
		{
			title: 'Pasta',
			img: '/img/pas.jpg',
			para: 'Pasta is made up of wheat flour dough mixed with water or eggs',
			price: '500',
			availability:'Out of stock',
			type: 'breakfast',
			id: 14,
			
		},
		{
			title: 'Prawn-biryani',
			img: '/img/fra.jpg',
			para: 'Prawn biryani, also known as shrimp biryani,made up of fried onions, and basmati rice',
			price: '1500',
			availability:'Available',
			type: 'dinner',
			id: 15,
			
		},
		{
			title: 'Desert',
			img: '/img/Des.jpg',
			para: 'Desert can refer to sweets like biscuits, cakes, cookies, custards, gelatins',
			price: '1500',
			availability:'Available',
			type: 'dinner',
			id: 16,
			
		},
		{
			title: 'chicken-shawarma',
			img: '/img/sar.jpg',
			para: 'Shawarma is the Middle Eastern dish of shaved pieces of spit roasted',
			price: '150',
			availability:'Available',
			type: 'dinner',
			id: 17,
			
		},
		{
			title: 'pizza',
			img: '/img/piz.jpg',
			para: 'Pizza is an Italian dish consisting of a flat base of leavened dough',
			price: '200',
			availability:'Available',
			type: 'snacks',
			id: 18,
			
		},
		{
			title: 'Grilled-meat',
			img: '/img/gir.jpg',
			para: 'A cut of beef thats ideal for grilling, with a mild, beefy flavor&lean texture',
			price: '200',
			availability:'Available',
			type: 'dinner',
			id: 19,
			
		},
		{
			title: 'coffe',
			img: '/img/cof.jpg',
			para: 'Coffee is a beverage made from roasted coffee beans that is bitter&slightly acidic.',
			price: '65',
			availability:'Available',
			type: 'snacks',
			id: 20,
			
		},
		{
			title: 'Noodles',
			img: '/img/nod.jpg',
			para: 'Noodles are a type of food made from unleavened dough which is either rolled ',
			price: '400',
			availability:'Available',
			type: 'dinner',
			id: 21,
			
		},
	
		{
			title: 'FULL-Meals',
			img: '/img/lun1.jpg',
			para: 'Lunch – eaten around mid-day, usually between 11 am and 3 pm',
			price: '200',
			availability:'Available',
			type: 'lunch',
			id: 22,
		},
		{
			title: 'Veg-lunch',
			img: '/img/lun2.jpg',
			para: 'veggies-for-lunch-recipes. Easy Vegetable Recipes to Make Ahead for Lunch ',
			price: '400',
			availability:'Available',
			type: 'lunch',
			id: 23,
		},
		{
			title: 'Sandwich',
			img: '/img/bre1.jpg',
			para: 'A breakfast sandwich is a sandwich made with breakfast foods',
			price: '300',
			availability:'Available',
			type: 'breakfast',
			id: 24,
		},
		{
			title: 'Veg-Salad',
			img: '/img/bre2.jpg',
			para: ' Breakfast salads are a great way to start your day with nutrient-dense foods.',
			price: '400',
			availability:'Available',
			type: 'breakfast',
			id: 25,
		},
		{
			title: 'Milk-shake',
			img: '/img/lun3.jpg',
			para: 'healthy drinks that are delicious alternatives to soda! Try homemade infused waters',
			price: '400',
			availability:'Available',
			type: 'lunch',
			id: 26,
		},
		{
			title: 'Grilled-ribs',
			img: '/img/chintu1.jpg',
			para: 'Just coat the ribs in the spice rub, wrap them in foil, and stick them on the grill. ',
			price: '3000',
			availability:'Available',
			type: 'dinner',
			id: 27,
		},
		{
			title: 'Meaty-vegetables',
			img: '/img/chintu2.jpg',
			para: 'Beef, pork and lamb all go well with a roasted veggies pan or stirfry veggies.',
			price: '3000',
			availability:'Available',
			type: 'dinner',
			id: 28,
		},
		{
			title: 'Meaty-vegetables',
			img: '/img/chintu3.jpg',
			para: 'Vegetable salads, also known as green salads,  with some cooked ingredients',
			price: '300',
			availability:'Available',
			type: 'lunch',
			id: 29,
		},
		{
			title: 'vegetables-salad',
			img: '/img/chintu3.jpg',
			para: 'Vegetable salads, also known as green salads,  with some cooked ingredients',
			price: '300',
			availability:'Available',
			type: 'dinner',
			id: 30,
		},
		{
			title: 'Sliced-potatoes',
			img: '/img/chintu4.jpg',
			para: 'Potato bread, tends to have a higher fiber content compared to white bread, ',
			price: '300',
			availability:'Available',
			type: 'breakfast',
			id: 31,
		},
		{
			title: 'cooked-food',
			img: '/img/chintu5.jpg',
			para: 'Cooked food is food that has been prepared using heat, boiling, frying, or other methods ',
			price: '300',
			availability:'Available',
			type: 'lunch',
			id: 32,
		},
		{
			title: 'cooked-Meals',
			img: '/img/chintu6.jpg',
			para: 'Cooked food is food that has been prepared using heat, boiling, frying, or other methods ',
			price: '500',
			availability:'Available',
			type: 'lunch',
			id: 33,
		},
		{
			title: 'Fruit-salad',
			img: '/img/chintu7.jpg',
			para: 'This fantastic fruit salad combines  and berries in a sweet citrusy sauce for a colorful dessert.',
			price: '500',
			availability:'Available',
			type: 'breakfast',
			id: 34,
		},
		{
			title: 'Bakesd-Pastry',
			img: '/img/chintu8.jpg',
			para: 'Pastry is a baked food made from a dough of flour, water, and shortening, which can be sweet or savory',
			price: '500',
			availability:'Available',
			type: 'breakfast',
			id: 35,
		},
		{
			title: 'Juicy-chicken',
			img: '/img/chintu9.jpg',
			para: 'Tender and full-flavored, our simple and easy-baked chicken breast recipe uses skinless and boneless',
			price: '1500',
			availability:'Available',
			type: 'lunch',
			id: 36,
		},
		{
			title: 'Garlic-bread',
			img: '/img/chintu10.jpg',
			para: 'Garlic bread: Made with flour, cheese, garlic, spices, and vegetables like capsicum or sweet corn',
			price: '500',
			availability:'Available',
			type: 'breakfast',
			id: 37,
		},
		{
			title: 'Chicken fry',
			img: '/img/chintu11.jpg',
			para: 'Diced chicken and chicken strips tend to take around 8 minutes to cook all the way through.',
			price: '1500',
			availability:'Available',
			type: 'lunch',
			id: 38,
		},
		{
			title: 'Grilled-fish',
			img: '/img/chintu12.jpg',
			para: ' Grilled fish recipe has a basic lemon pepper marinate and it taste simple delicious.',
			price: '1500',
			availability:'Available',
			type: 'lunch',
			id: 39,
		},
		{
			title: 'Grilled-vegetables',
			img: '/img/chintu13.jpg',
			para: 'These grilled vegetables are the easiest summer side dish!ightly charred, tender, and flavorful.',
			price: '500',
			availability:'Available',
			type: 'lunch',
			id: 40,
		},
		{
			title: 'Pancakes',
			img: '/img/chintu14.jpg',
			para: 'A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs,',
			price: '500',
			availability:'Available',
			type: 'snacks',
			id: 41,
		},
		{
			title: 'Strawberry cake',
			img: '/img/chintu15.jpg',
			para: 'This strawberry cake is a great way to use up extra strawberries &one of simplest, most delicious cakes ',
			price: '500',
			availability:'Available',
			type: 'snacks',
			id: 42,
		},
		{
			title: 'Toasted bread-berry',
			img: '/img/chintu16.jpg',
			para: 'bread, blueberry toast is a creamy. With toasted white bread, thick yogurt, and sweet blueberry',
			price: '200',
			availability:'Available',
			type: 'snacks',
			id: 43,
		},
		{
			title: 'Fruity-Egg',
			img: '/img/chintu17.jpg',
			para: 'Egg salad is a dish consisting of chopped hard-boiled or scrambled eggs, mustard',
			price: '500',
			availability:'Available',
			type: 'breakfast',
			id: 44,
		},
		{
			title: 'Straberry shake',
			img: '/img/chintu18.jpg',
			para: 'A strawberry shake recipe like mom used to make. Easy and refreshing, especially on hot days.',
			price: '100',
			availability:'Available',
			type: 'snacks',
			id: 45,
		},
		{
			title: 'Desert',
			img: '/img/chintu19.jpg',
			para: 'Roasted strawberry crumble. Super Food Ideas · Maltesers tiramisu · Low-fat mango fool ',
			price: '120',
			availability:'Available',
			type: 'snacks',
			id: 46,
		},
		{
			title: 'Roasetd chicken',
			img: '/img/chintu20.jpg',
			para: 'Roast chicken is chicken prepared as food by roasting whether in a home kitchen, over a fire',
			price: '1200',
			availability:'Available',
			type: 'dinner',
			id: 47,
		},
		{
			title: 'Tomato curry',
			img: '/img/chintu21.jpg',
			para: 'This is a spiced and mildly tangy Tomato Curry made with ground tomatoes, onions',
			price: '150',
			availability:'Available',
			type: 'lunch',
			id: 48,
		},
		{
			title: 'Boiled vegetables',
			img: '/img/chintu22.jpg',
			para: 'ngredients of Boiled Green Vegetables · 4 cup cabbage · 4 cup bean · 4 cup cauliflower',
			price: '300',
			availability:'Available',
			type: 'lunch',
			id: 49,
		},
		{
			title: 'Safron fish',
			img: '/img/chintu23.jpg',
			para: 'A fish fry is a meal containing battered or breaded fried fish. It usually also includes french fries',
			price: '500',
			availability:'Available',
			type: 'dinner',
			id: 50,
		},
];